Task 1: 
 
1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions. 
 
 

In [1]:
def divide(a, b):
    try:
        c = a / b
    except ZeroDivisionError:
        print("Divided By Zero! Invalid Divisor")
    else:
        print("Division:", c)


a = int(input("Enter the Dividend:"))
b = int(input("Enter the Divisor:"))
divide(a, b)


Enter the Dividend:5
Enter the Divisor:0
Divided By Zero! Invalid Divisor


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"] 
 
Output should come as below: 
 
Americans  play Baseball. Americans  play Cricket. Americans  watch Baseball. Americans  watch Cricket. Indians play Baseball. Indians play Cricket. Indians watch Baseball. Indians watch Cricket. 

In [2]:
subject = ["Americans", "Indians"]
verb = ["Play", "watch"]
obj = ["Baseball", "cricket"]
sentences = [(sub+" " + vb + " " + ob + ".") for sub in subject for vb in verb for ob in obj]
for sentence in sentences:
    print(sentence)


Americans Play Baseball.
Americans Play cricket.
Americans watch Baseball.
Americans watch cricket.
Indians Play Baseball.
Indians Play cricket.
Indians watch Baseball.
Indians watch cricket.


TASK 2

Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.  
 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 
 
 

In [1]:
import numpy as np


def power(l, N):
    x = np.array(l)
    return np.column_stack([x ** (N - 1 - i) for i in range(N)])


print(power([1, 2, 7, 9], 5))


[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [2401  343   49    7    1]
 [6561  729   81    9    1]]
